services:
  - type: web
    name: atmosphere-weather-app
    env: node
    region: ohio
    buildCommand: "cd backend && npm install && cd ../frontend && npm install && npm run build"
    startCommand: "cd backend && NODE_ENV=production node server.js"
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGO_URI
        sync: false
      - key: OPENWEATHER_API_KEY
        sync: false
      - key: GROQ_API_KEY
        sync: false
      - key: YOUTUBE_API_KEY
        sync: false
      - key: GOOGLE_MAPS_KEY
        sync: false
